language: java
env:
  - TEST_SUITE=test_core
  - TEST_SUITE=test_site
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DoAH/3+kHNtoQkb4/iggDsF08PXMdu8FEOSih3w/GgYas93CNsvGs2ymMg4dcazd25zzoGIw9WrYMvTGUUdHY6Hg0k7yKJWr5sNru1AGJ/L/aSrr/2LsM4pGXFsvxQtnWRIDBMS9nzdrf83iUXvpNdVktCoRAK4jvw955M7LCRs="
script: "ant $TEST_SUITE"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu

addons:
  coverity_scan:
    project:
      name: "sul-dlss/solrmarc-sw"
      description: "Stanford SearchWorks fork of SolrMarc"
    notification_email: ndushay@stanford.edu
    build_command_prepend:
    build_command: "ant compile_site"
    branch_pattern: coverity_scan
