language: java
env:
  - TEST_SUITE=test_core
  - TEST_SUITE=test_site
script: "ant $TEST_SUITE"
jdk:
  # prod, test: Java HostSpot 64-bit Server VM;
  #   Java(TM) SE Runtime Environment (build 1.6.0_33-b03)
  - openjdk6
#  - openjdk7
#  - oraclejdk7
#  - oraclejdk8

notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu

sudo: false